---
dist: bionic

addons:
  apt:
    packages:
      - graphviz 

language: java
jdk: openjdk11

cache:
  directories:
  - $HOME/.m2

script: mvn clean verify -DskipTests

before_deploy:
  - "sed -i 'H;${x;s/^\n//;s/dependencies: \[/&\n{ src: \x27http:\/\/remote.jugspeakers.online:3001\/socket.io\/socket.io.js\x27, async: true }\n{ src: \x27http:\/\/remote.jugspeakers.online:3001\/remote.js\x27, async: true }\n/;p;}' slides/target/generated-slides/index.html"

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GH_TOKEN
  local_dir: slides/target/generated-slides
  on:
    branch: master
